on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: siphon-static    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: https://registry.npmjs.org/
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
